textos = {
    "es": {
        "titulo": "Dashboard: Turismo y PIB",
        "seleccion_pais": "Selecciona un país:",
        "apilar": "¿Apilar gráfico PIB y Turismo?",
        "check_apilar": " Apilar",
        "ajustes": "⚙ Ajustes",
        "idioma_label": "Selecciona el idioma que prefieres para los países:",
        "cerrar": "Cerrar",
        "grafico_titulo_apilado": "Aporte del turismo al PIB de {pais} (apilado)",
        "grafico_titulo_no_apilado": "Aporte del turismo al PIB de {pais} (no apilado)",
        "eje_x": "Año",
        "eje_y": "PIB (US)",
        "leyenda": "Fuente",
        "turismo": "Turismo",
        "pib_restante": "PIB restante",
        "titulo_plot2": "Mapa de llegadas turísticas",
        "label_anio_plot2": "Selecciona un año:",
        "eje_x_valor_plot4": "Valor",
        "eje_y_pais_plot4": "País",
        "indicadores_plot4": {
            "arrivals": "Llegadas internacionales",
            "departures": "Salidas internacionales",
            "receipts_total": "Ingresos totales por turismo (US$)",
            "receipts_travel": "Ingresos por actividades del viaje (US$)",
            "receipts_transport": "Ingresos por transporte de pasajeros (US$)",
            "expenditures_total": "Gastos totales por turismo (US$)",
            "expenditures_travel": "Gastos en actividades del viaje (US$)",
            "expenditures_transport": "Gastos en transporte de pasajeros (US$)",
            "receipts_exports": "Ingresos por turismo (% exportaciones)",
            "expenditures_imports": "Gastos por turismo (% importaciones)"
        }

    },
    "en": {
        "titulo": "Dashboard: Tourism and GDP",
        "seleccion_pais": "Select a country:",
        "apilar": "Stack GDP and Tourism graph?",
        "check_apilar": " Stack",
        "ajustes": "⚙ Settings",
        "idioma_label": "Choose your preferred language for countries:",
        "cerrar": "Close",
        "grafico_titulo_apilado": "Tourism's contribution to {pais} GDP (stacked)",
        "grafico_titulo_no_apilado": "Tourism's contribution to {pais} GDP (not stacked)",
        "eje_x": "Year",
        "eje_y": "GDP (US)",
        "leyenda": "Source",
        "turismo": "Tourism",
        "pib_restante": "Remaining GDP",
        "titulo_plot2": "Tourist arrivals map",
        "label_anio_plot2": "Select a year:",
        "eje_x_valor_plot4": "Value",
        "eje_y_pais_plot4": "Country",
        "indicadores_plot4": {
            "arrivals": "International arrivals",
            "departures": "International departures",
            "receipts_total": "Total tourism receipts (US$)",
            "receipts_travel": "Travel items receipts (US$)",
            "receipts_transport": "Passenger transport receipts (US$)",
            "expenditures_total": "Total tourism expenditures (US$)",
            "expenditures_travel": "Travel items expenditures (US$)",
            "expenditures_transport": "Passenger transport expenditures (US$)",
            "receipts_exports": "Tourism receipts (% exports)",
            "expenditures_imports": "Tourism expenditures (% imports)"
        }
    }
}