traducciones = {
    "Algeria": "Argelia",
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Austria": "Austria",
    "Bahamas, The": "Las Bahamas",
    "Bangladesh": "Bangladés",
    "Barbados": "Barbados",
    "Belgium": "Bélgica",
    "Belize": "Belice",
    "Benin": "Benín",
    "Bermuda": "Bermudas",
    "Bolivia": "Bolivia",
    "Botswana": "Botsuana",
    "Brazil": "Brasil",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cameroon": "Camerún",
    "Canada": "Canadá",
    "Central African Republic": "República Centroafricana",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Congo, Dem. Rep.": "República Democrática del Congo",
    "Congo, Rep.": "República del Congo",
    "Costa Rica": "Costa Rica",
    "Cote d'Ivoire": "Costa de Marfil",
    "Denmark": "Dinamarca",
    "Dominican Republic": "República Dominicana",
    "Ecuador": "Ecuador",
    "Egypt, Arab Rep.": "Egipto",
    "Eswatini": "Esuatini",
    "Ethiopia": "Etiopía",
    "Fiji": "Fiyi",
    "Finland": "Finlandia",
    "France": "Francia",
    "Gabon": "Gabón",
    "Germany": "Alemania",
    "Ghana": "Ghana",
    "Greece": "Grecia",
    "Guatemala": "Guatemala",
    "Guyana": "Guyana",
    "Haiti": "Haití",
    "Honduras": "Honduras",
    "Hong Kong SAR, China": "Hong Kong",
    "Iceland": "Islandia",
    "India": "India",
    "Iran, Islamic Rep.": "Irán",
    "Iraq": "Irak",
    "Ireland": "Irlanda",
    "Israel": "Israel",
    "Italy": "Italia",
    "Jamaica": "Jamaica",
    "Japan": "Japón",
    "Kenya": "Kenia",
    "Korea, Rep.": "Corea del Sur",
    "Lesotho": "Lesoto",
    "Liberia": "Liberia",
    "Libya": "Libia",
    "Luxembourg": "Luxemburgo",
    "Madagascar": "Madagascar",
    "Malaysia": "Malasia",
    "Mauritius": "Mauricio",
    "Mexico": "México",
    "Morocco": "Marruecos",
    "Myanmar": "Birmania",
    "Nepal": "Nepal",
    "Netherlands": "Países Bajos",
    "New Zealand": "Nueva Zelanda",
    "Nicaragua": "Nicaragua",
    "Niger": "Níger",
    "Nigeria": "Nigeria",
    "Norway": "Noruega",
    "Oman": "Omán",
    "Pakistan": "Pakistán",
    "Panama": "Panamá",
    "Papua New Guinea": "Papúa Nueva Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Perú",
    "Philippines": "Filipinas",
    "Portugal": "Portugal",
    "Puerto Rico (US)": "Puerto Rico",
    "Rwanda": "Ruanda",
    "Saudi Arabia": "Arabia Saudita",
    "Senegal": "Senegal",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leona",
    "Singapore": "Singapur",
    "Somalia": "Somalia",
    "South Africa": "Sudáfrica",
    "Spain": "España",
    "Sri Lanka": "Sri Lanka",
    "St. Kitts and Nevis": "San Cristóbal y Nieves",
    "St. Vincent and the Grenadines": "San Vicente y las Granadinas",
    "Sudan": "Sudán",
    "Suriname": "Surinam",
    "Sweden": "Suecia",
    "Switzerland": "Suiza",
    "Syrian Arab Republic": "Siria",
    "Tanzania": "Tanzania",
    "Thailand": "Tailandia",
    "Togo": "Togo",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "Turkiye": "Turquía",
    "Uganda": "Uganda",
    "United Kingdom": "Reino Unido",
    "United States": "Estados Unidos",
    "Uruguay": "Uruguay",
    "Venezuela, RB": "Venezuela",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabue",
    "Albania": "Albania",
    "Angola": "Angola",
    "Bulgaria": "Bulgaria",
    "Cabo Verde": "Cabo Verde",
    "Comoros": "Comoras",
    "Malawi": "Malaui",
    "Mongolia": "Mongolia",
    "Namibia": "Namibia",
    "St. Lucia": "Santa Lucía",
    "Macao SAR, China": "Macao",
    "Isle of Man": "Isla de Man",
    "Lao PDR": "Laos",
    "Djibouti": "Yibuti",
    "Viet Nam": "Vietnam",
    "Aruba": "Aruba",
    "Georgia": "Georgia",
    "Romania": "Rumania",
    "Turkmenistan": "Turkmenistán",
    "Ukraine": "Ucrania",
    "Uzbekistan": "Uzbekistán",
    "Lebanon": "Líbano",
    "Russian Federation": "Rusia",
    "Armenia": "Armenia",
    "Azerbaijan": "Azerbaiyán",
    "Belarus": "Bielorrusia",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Croatia": "Croacia",
    "Czechia": "Chequia",
    "Kazakhstan": "Kazajistán",
    "Kyrgyz Republic": "Kirguistán",
    "Moldova": "Moldavia",
    "North Macedonia": "Macedonia del Norte",
    "Poland": "Polonia",
    "Slovak Republic": "Eslovaquia",
    "Slovenia": "Eslovenia",
    "Tajikistan": "Tayikistán",
    "Timor-Leste": "Timor Oriental",
    "Yemen, Rep.": "Yemen",
    "Mozambique": "Mozambique",
    "Eritrea": "Eritrea",
    "Estonia": "Estonia",
    "West Bank and Gaza": "Cisjordania y Gaza",
    "Latvia": "Letonia",
    "Lithuania": "Lituania",
    "Serbia": "Serbia",
    "British Virgin Islands": "Islas Vírgenes Británicas",
    "Turks and Caicos Islands": "Islas Turcas y Caicos",
    "Sint Maarten (Dutch part)": "Sint Maarten (parte holandesa)",
    "American Samoa": "Samoa Americana",
    "Cayman Islands": "Islas Caimán",
    "Curacao": "Curazao",
    "Guam": "Guam",
    "Northern Mariana Islands": "Islas Marianas del Norte",
    "San Marino": "San Marino",
    "Virgin Islands (U.S.)": "Islas Vírgenes de EE. UU.",
    "Montenegro": "Montenegro",
    "Channel Islands": "Islas del Canal",
    "Afghanistan": "Afganistán",
    "Kosovo": "Kosovo",
    "South Sudan": "Sudán del Sur",
    "St. Martin (French part)": "San Martín (parte francesa)",
    "Andorra": "Andorra",
    "Antigua and Barbuda": "Antigua y Barbuda",
    "Bahrain": "Baréin",
    "Bhutan": "Bután",
    "Brunei Darussalam": "Brunéi",
    "Cambodia": "Camboya",
    "Cuba": "Cuba",
    "Cyprus": "Chipre",
    "Dominica": "Dominica",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guinea Ecuatorial",
    "Faroe Islands": "Islas Feroe",
    "French Polynesia": "Polinesia Francesa",
    "Gambia, The": "Gambia",
    "Greenland": "Groenlandia",
    "Grenada": "Granada",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bisáu",
    "Hungary": "Hungría",
    "Indonesia": "Indonesia",
    "Jordan": "Jordania",
    "Kiribati": "Kiribati",
    "Kuwait": "Kuwait",
    "Liechtenstein": "Liechtenstein",
    "Maldives": "Maldivas",
    "Mali": "Malí",
    "Malta": "Malta",
    "Marshall Islands": "Islas Marshall",
    "Mauritania": "Mauritania",
    "Micronesia, Fed. Sts.": "Micronesia",
    "Monaco": "Mónaco",
    "Nauru": "Nauru",
    "New Caledonia": "Nueva Caledonia",
    "Palau": "Palaos",
    "Qatar": "Catar",
    "Samoa": "Samoa",
    "Sao Tome and Principe": "Santo Tomé y Príncipe",
    "Solomon Islands": "Islas Salomón",
    "Tonga": "Tonga",
    "Tunisia": "Túnez",
    "Tuvalu": "Tuvalu",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "Vanuatu": "Vanuatu"
}

traducciones_inversas = {v: k for k, v in traducciones.items()}

def traducir_pais(nombre_pais):
    return traducciones.get(nombre_pais)

def traducir_pais_inverso(nombre_pais_es):
    return traducciones_inversas.get(nombre_pais_es)

def verificar_paises_sin_traduccion(df, diccionario):
    paises_dataset = set(df["Country Name"].unique())
    paises_traducidos = set(diccionario.keys())

    # Países que están en el dataset pero no en el diccionario
    sin_traduccion = paises_dataset - paises_traducidos

    if sin_traduccion:
        print("Estos países NO tienen traducción en el diccionario:")
        for pais in sorted(sin_traduccion):
            print(f"- {pais}")
    else:
        print("Todos los países del dataset tienen traducción en el diccionario.")


if __name__ == "__main__":
    from cargarDataframes import df1
    df = df1(path = "../Datasets/P_Data_Extract_From_World_Development_Indicators.xlsx")
    verificar_paises_sin_traduccion(df, traducciones)
    pais = "Maldives"
    traduccion = traducir_pais(pais)
    if traduccion:
        print(f"La traducción de '{traducir_pais_inverso(traduccion)}' es '{traduccion}'.")
    else:
        print(f"No se encontró traducción para '{pais}'.")
